### ISSUE TITLE
[Improve]: Fix Lint Rules

### ISSUE THREAD

**Issue by blendthink** [blendthink/elixir#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Motivation

The rules used by Flutter are applied.

### Proposal

```yaml
linter:
  rules:
    # Error Rules
    - always_use_package_imports
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_returning_null_for_future
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    #- avoid_web_libraries_in_flutter # Use with Flutter
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - control_flow_in_finally
    #- diagnostic_describe_all_properties # Use with Flutter
    #- discarded_futures # Taste
    - empty_statements
    - hash_and_equals
    #- invariant_booleans # Deprecated
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    #- no_logic_in_create_state # Use with Flutter
    #- prefer_relative_imports # incompatible with `always_use_package_imports`
    - prefer_void_to_null
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements
    - unrelated_type_equality_checks
    - unsafe_html
    #- use_build_context_synchronously # Use with Flutter
    #- use_key_in_widget_constructors # Use with Flutter
    - valid_regexps

    # Style Rules
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - always_require_non_null_named_parameters
    #- always_specify_types # Taste
    - annotate_overrides
    #- avoid_annotating_with_dynamic # Taste
    #- avoid_as # Deprecated
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    - avoid_final_parameters
    - avoid_function_literals_in_foreach_calls
    - avoid_implementing_value_types
    - avoid_init_to_null
    - avoid_js_rounded_ints
    - avoid_multiple_declarations_per_line
    - avoid_null_checks_in_equality_operators
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_positional_boolean_parameters
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_renaming_method_parameters
    - avoid_returning_null
    - avoid_returning_null_for_void
    - avoid_returning_this
    - avoid_return_types_on_setters
    - avoid_setters_without_getters
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_types_on_closure_parameters
    #- avoid_unnecessary_containers # Use with Flutter
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cascade_invocations
    - cast_nullable_to_non_nullable
    #- combinators_ordering # Available from Dart 2.19
    - conditional_uri_does_not_exist
    - constant_identifier_names
    - curly_braces_in_flow_control_structures
    - deprecated_consistency
    - directives_ordering
    - do_not_use_environment
    - empty_catches
    - empty_constructor_bodies
    - eol_at_end_of_file
    - exhaustive_cases
    - file_names
    #- flutter_style_todos # Use with Flutter
    - implementation_imports
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - library_names
    - library_prefixes
    - library_private_types_in_public_api
    - lines_longer_than_80_chars
    - missing_whitespace_between_adjacent_strings
    - no_default_cases
    - non_constant_identifier_names
    - no_leading_underscores_for_library_prefixes
    - no_leading_underscores_for_local_identifiers
    - noop_primitive_operations
    - no_runtimeType_toString
    - null_check_on_nullable_type_parameter
    - null_closures
    - omit_local_variable_types
    - one_member_abstracts
    - only_throw_errors
    - overridden_fields
    - package_api_docs
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    #- prefer_asserts_with_message # Taste
    #- prefer_bool_in_asserts # Deprecated
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_contains
    #- prefer_double_quotes # incompatible with `prefer_single_quotes`
    - prefer_equal_for_default_values
    - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    #- prefer_final_parameters # Taste
    - prefer_foreach
    - prefer_for_elements_to_map_fromIterable
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_interpolation_to_compose_strings
    - prefer_int_literals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_mixin
    - prefer_null_aware_operators
    - prefer_null_aware_method_calls
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - provide_deprecation_message
    #- public_member_api_docs # Taste
    - recursive_getters
    - require_trailing_commas
    #- sized_box_for_whitespace # Use with Flutter
    #- sized_box_shrink_expand # Use with Flutter
    - slash_for_doc_comments
    #- sort_child_properties_last # Use with Flutter
    - sort_constructors_first
    - sort_unnamed_constructors_first
    #- super_goes_last # Deprecated
    - tighten_type_of_initializing_formals
    - type_annotate_public_apis
    - type_init_formals
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_constructor_name
    #- unnecessary_final # incompatible with `prefer_final_locals`
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_null_checks
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unnecessary_to_list_in_spreads
    #- unreachable_from_main # Available from Dart 2.19
    #- use_colored_box # Use with Flutter
    #- use_decorated_box # Use with Flutter
    - use_enums
    #- use_full_hex_values_for_flutter_colors # Use with Flutter
    - use_function_type_syntax_for_parameters
    #- use_if_null_to_convert_nulls_to_bools # Taste
    - use_is_even_rather_than_modulo
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_rethrow_when_possible
    - use_raw_strings
    - use_setters_to_change_properties
    - use_string_buffers
    #- use_string_in_part_of_directives # Available from Dart 2.19
    - use_super_parameters
    - use_test_throws_matchers
    - use_to_and_as_if_applicable
    - void_checks

    # Pub Rules
    - depend_on_referenced_packages
    - package_names
    - secure_pubspec_urls
    - sort_pub_dependencies
```
